{
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["# Momentum Portfolio Analysis"],
        },
        {
            "cell_type": "code",
            "execution_count": 12,
            "metadata": {},
            "outputs": [],
            "source": [
                'portfolio_id = "6f3f7842-344d-41a1-bec7-60bb935a52da"'
            ],
        },
        {"cell_type": "markdown", "metadata": {}, "source": ["### imports"]},
        {
            "cell_type": "code",
            "execution_count": 2,
            "metadata": {},
            "outputs": [],
            "source": [
                "import alpaca_trade_api as tradeapi\n",
                "from liualgotrader.models.portfolio import Portfolio",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["### load SP500 data"],
        },
        {
            "cell_type": "code",
            "execution_count": 9,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "table=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')\n",
                "sp500_df = table[0]",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["### load portfolio data"],
        },
        {
            "cell_type": "code",
            "execution_count": 26,
            "metadata": {},
            "outputs": [],
            "source": [
                "df = await Portfolio.load(portfolio_id)\n",
                "\n",
                "for i, row in df.iterrows():\n",
                "    df.loc[df.symbol == row.symbol, 'Security'] = sp500_df.loc[sp500_df.Symbol == row.symbol, 'Security'].values[0]\n",
                "    df.loc[df.symbol == row.symbol, 'Sector'] = sp500_df.loc[sp500_df.Symbol == row.symbol, 'GICS Sector'].values[0]\n",
                "    df.loc[df.symbol == row.symbol, 'Industry'] = sp500_df.loc[sp500_df.Symbol == row.symbol, 'GICS Sub-Industry'].values[0]",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": 27,
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/html": [
                            "<div>\n",
                            "<style scoped>\n",
                            "    .dataframe tbody tr th:only-of-type {\n",
                            "        vertical-align: middle;\n",
                            "    }\n",
                            "\n",
                            "    .dataframe tbody tr th {\n",
                            "        vertical-align: top;\n",
                            "    }\n",
                            "\n",
                            "    .dataframe thead th {\n",
                            "        text-align: right;\n",
                            "    }\n",
                            "</style>\n",
                            '<table border="1" class="dataframe">\n',
                            "  <thead>\n",
                            '    <tr style="text-align: right;">\n',
                            "      <th></th>\n",
                            "      <th>symbol</th>\n",
                            "      <th>qty</th>\n",
                            "      <th>rank</th>\n",
                            "      <th>Security</th>\n",
                            "      <th>Sector</th>\n",
                            "      <th>Industry</th>\n",
                            "    </tr>\n",
                            "  </thead>\n",
                            "  <tbody>\n",
                            "    <tr>\n",
                            "      <th>0</th>\n",
                            "      <td>AAP</td>\n",
                            "      <td>2</td>\n",
                            "      <td>0.0000098497</td>\n",
                            "      <td>Advance Auto Parts</td>\n",
                            "      <td>Consumer Discretionary</td>\n",
                            "      <td>Automotive Retail</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>1</th>\n",
                            "      <td>JNJ</td>\n",
                            "      <td>4</td>\n",
                            "      <td>0.0000028493</td>\n",
                            "      <td>Johnson &amp; Johnson</td>\n",
                            "      <td>Health Care</td>\n",
                            "      <td>Pharmaceuticals</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>2</th>\n",
                            "      <td>ORLY</td>\n",
                            "      <td>1</td>\n",
                            "      <td>0.0000018255</td>\n",
                            "      <td>O'Reilly Automotive</td>\n",
                            "      <td>Consumer Discretionary</td>\n",
                            "      <td>Specialty Stores</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>3</th>\n",
                            "      <td>FBHS</td>\n",
                            "      <td>4</td>\n",
                            "      <td>0.0000011700</td>\n",
                            "      <td>Fortune Brands Home &amp; Security</td>\n",
                            "      <td>Industrials</td>\n",
                            "      <td>Building Products</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>4</th>\n",
                            "      <td>NDAQ</td>\n",
                            "      <td>3</td>\n",
                            "      <td>0.0000010807</td>\n",
                            "      <td>Nasdaq, Inc.</td>\n",
                            "      <td>Financials</td>\n",
                            "      <td>Financial Exchanges &amp; Data</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>5</th>\n",
                            "      <td>PEP</td>\n",
                            "      <td>5</td>\n",
                            "      <td>6.523E-7</td>\n",
                            "      <td>PepsiCo Inc.</td>\n",
                            "      <td>Consumer Staples</td>\n",
                            "      <td>Soft Drinks</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>6</th>\n",
                            "      <td>VAR</td>\n",
                            "      <td>20</td>\n",
                            "      <td>5.953E-7</td>\n",
                            "      <td>Varian Medical Systems</td>\n",
                            "      <td>Health Care</td>\n",
                            "      <td>Health Care Equipment</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>7</th>\n",
                            "      <td>OTIS</td>\n",
                            "      <td>7</td>\n",
                            "      <td>5.306E-7</td>\n",
                            "      <td>Otis Worldwide</td>\n",
                            "      <td>Industrials</td>\n",
                            "      <td>Industrial Machinery</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>8</th>\n",
                            "      <td>MMM</td>\n",
                            "      <td>3</td>\n",
                            "      <td>4.162E-7</td>\n",
                            "      <td>3M Company</td>\n",
                            "      <td>Industrials</td>\n",
                            "      <td>Industrial Conglomerates</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>9</th>\n",
                            "      <td>DRE</td>\n",
                            "      <td>11</td>\n",
                            "      <td>3.895E-7</td>\n",
                            "      <td>Duke Realty Corp</td>\n",
                            "      <td>Real Estate</td>\n",
                            "      <td>Industrial REITs</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>10</th>\n",
                            "      <td>CL</td>\n",
                            "      <td>8</td>\n",
                            "      <td>2.719E-7</td>\n",
                            "      <td>Colgate-Palmolive</td>\n",
                            "      <td>Consumer Staples</td>\n",
                            "      <td>Household Products</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>11</th>\n",
                            "      <td>MDLZ</td>\n",
                            "      <td>12</td>\n",
                            "      <td>2.684E-7</td>\n",
                            "      <td>Mondelez International</td>\n",
                            "      <td>Consumer Staples</td>\n",
                            "      <td>Packaged Foods &amp; Meats</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>12</th>\n",
                            "      <td>EXPD</td>\n",
                            "      <td>5</td>\n",
                            "      <td>7.69E-8</td>\n",
                            "      <td>Expeditors</td>\n",
                            "      <td>Industrials</td>\n",
                            "      <td>Air Freight &amp; Logistics</td>\n",
                            "    </tr>\n",
                            "    <tr>\n",
                            "      <th>13</th>\n",
                            "      <td>KO</td>\n",
                            "      <td>10</td>\n",
                            "      <td>1.36E-8</td>\n",
                            "      <td>Coca-Cola Company</td>\n",
                            "      <td>Consumer Staples</td>\n",
                            "      <td>Soft Drinks</td>\n",
                            "    </tr>\n",
                            "  </tbody>\n",
                            "</table>\n",
                            "</div>",
                        ],
                        "text/plain": [
                            "   symbol  qty          rank                        Security  \\\n",
                            "0     AAP    2  0.0000098497              Advance Auto Parts   \n",
                            "1     JNJ    4  0.0000028493               Johnson & Johnson   \n",
                            "2    ORLY    1  0.0000018255             O'Reilly Automotive   \n",
                            "3    FBHS    4  0.0000011700  Fortune Brands Home & Security   \n",
                            "4    NDAQ    3  0.0000010807                    Nasdaq, Inc.   \n",
                            "5     PEP    5      6.523E-7                    PepsiCo Inc.   \n",
                            "6     VAR   20      5.953E-7          Varian Medical Systems   \n",
                            "7    OTIS    7      5.306E-7                  Otis Worldwide   \n",
                            "8     MMM    3      4.162E-7                      3M Company   \n",
                            "9     DRE   11      3.895E-7                Duke Realty Corp   \n",
                            "10     CL    8      2.719E-7               Colgate-Palmolive   \n",
                            "11   MDLZ   12      2.684E-7          Mondelez International   \n",
                            "12   EXPD    5       7.69E-8                      Expeditors   \n",
                            "13     KO   10       1.36E-8               Coca-Cola Company   \n",
                            "\n",
                            "                    Sector                    Industry  \n",
                            "0   Consumer Discretionary           Automotive Retail  \n",
                            "1              Health Care             Pharmaceuticals  \n",
                            "2   Consumer Discretionary            Specialty Stores  \n",
                            "3              Industrials           Building Products  \n",
                            "4               Financials  Financial Exchanges & Data  \n",
                            "5         Consumer Staples                 Soft Drinks  \n",
                            "6              Health Care       Health Care Equipment  \n",
                            "7              Industrials        Industrial Machinery  \n",
                            "8              Industrials    Industrial Conglomerates  \n",
                            "9              Real Estate            Industrial REITs  \n",
                            "10        Consumer Staples          Household Products  \n",
                            "11        Consumer Staples      Packaged Foods & Meats  \n",
                            "12             Industrials     Air Freight & Logistics  \n",
                            "13        Consumer Staples                 Soft Drinks  ",
                        ],
                    },
                    "execution_count": 27,
                    "metadata": {},
                    "output_type": "execute_result",
                }
            ],
            "source": ["df"],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}
