#!/bin/bash
set -e


export ALPACA_PAPER_BASEURL="https://paper-api.alpaca.markets"
export ALPACA_PAPER_API_KEY="PKO3OSD9LU9GTQPL69GO"
export ALPACA_PAPER_API_SECRET="chnPFlGXbY4Y4QAAZ3Q7MJHxkxBYB30CQZNVZTaj"

export ALPACA_LIVE_BASEURL="https://api.alpaca.markets"
export ALPACA_LIVE_API_KEY="AKVKN4TLUUS5MZO5KYLM"
export ALPACA_LIVE_API_SECRET="nkK2UmvE1kTFFw1ZlaqDmwCyiuCu7OOeB5y2La/X"